// All user-facing strings live here. Edit copy in one place.
//
// Keep the marketing voice consistent: short, energetic, no jargon, no
// emoji parties. The unicorn is the brand mark — use it once per command
// run (top banner), not on every line.

import 'version.dart';

const _utopiaUrl = 'https://utopiasoft.io';
const _cliRepoUrl = 'https://github.com/Utopia-USS/utopia-cli';
const _skillsRepoSlug = 'Utopia-USS/utopia-flutter-skills';
const _skillsRepoUrl = 'https://github.com/$_skillsRepoSlug';
const _utopiaHooksUrl = 'https://pub.dev/packages/utopia_hooks';
const _utopiaArchUrl = 'https://pub.dev/packages/utopia_arch';

/// Marketplace identifier for the Utopia Flutter Skills marketplace.
const utopiaSkillsMarketplaceSlug = _skillsRepoSlug;

/// Banner printed once per command run (above any output).
String get banner => '🦄 Utopia CLI v$packageVersion';

/// Footer printed at the end of a successful `create` run.
const createFooter = 'Built with ❤︎ by Utopia · $_utopiaUrl';

/// Next-steps block printed after a successful `create flutter_app` run.
String createNextSteps({required String projectName, required bool skillsEnabled}) {
  final lines = <String>[
    '→ cd $projectName',
    '→ flutter run',
    '',
    'Next:',
    '  • Try the sample counter feature at lib/screen/counter/',
  ];
  if (skillsEnabled) {
    lines.add('  • Open Claude Code and run /utopia-hooks to scaffold your next screen');
  }
  lines
    ..add('  • Read DEVELOPMENT.md for the Screen/State/View pattern overview')
    ..add('')
    ..add(createFooter);
  return lines.join('\n');
}

/// "Coming soon" message printed by Phase-2 stub commands.
String comingSoon(String commandName) =>
    'Coming soon — `utopia $commandName` is on the roadmap.\n'
    'Track progress at $_cliRepoUrl/issues.';

/// Update-available banner, shown by the command runner when a newer
/// version is on pub.dev.
String updateAvailable(String latestVersion) => '''
Update available! $packageVersion → $latestVersion
Changelog: $_cliRepoUrl/releases/tag/v$latestVersion
Run `utopia update` to install.''';

/// Deprecation notice shown when users invoke the old `utopia_arch_cli`
/// executable name. Removed in 0.3.0.
const deprecatedExecutableNotice =
    'Notice: `utopia_arch_cli` has been renamed to `utopia`. The old name '
    'still works for now and will be removed in v0.3.0. Run `utopia` going '
    'forward.';

/// Readme footer injected into generated projects.
const generatedReadmeFooter = '''
---
Generated by [Utopia CLI]($_cliRepoUrl) 🦄 · Powered by [utopia_hooks]($_utopiaHooksUrl) + [utopia_arch]($_utopiaArchUrl)
''';

/// Inline link to the skills marketplace, used in generated docs.
const skillsMarketplaceUrl = _skillsRepoUrl;
